feat(combobox): implement on open event for combobox
momentum-design/momentum-ui pull request #1354
Opened 2022-09-30 10:17 UTC by rathnavel

## Description
1. "combobox-on-expand" dispatch event is implemented. This event will trigger every time when we open the Combobox. 
2. New property "show-loader" has been implemented. This will be helpful to show the custom loader slot content. 

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots:
**Before** (If applicable):

**After**:

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-09-30 11:26 UTC, parsoman commented
Please resolve the conflicts

2022-09-30 12:11 UTC, vikcool2pr submitted a review, later dismissed

2022-10-06 12:22 UTC, momeraj requested changes

2022-10-06 12:48 UTC, rathnavel commented on web-components/src/[sandbox]/examples/combobox.ts
> +  <h3>Custom Loader</h3>
@combobox-on-expand property has been added.

2022-10-06 12:50 UTC, momeraj approved these changes

2022-10-06 15:14 UTC, vikcool2pr commented on web-components/src/[sandbox]/examples/combobox.ts
> +  console.log("combobox-on-expand: ", e);
remove the console.

2022-10-07 02:41 UTC, merged