fix(button): button aria-popup and aria-collasped default value changed
momentum-design/momentum-ui pull request #1439
Opened 2023-03-29 12:14 UTC by arunmohanpk

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots:
**Before** (If applicable):

**After**:

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-03-30 05:12 UTC, vinitkumargoel submitted a review, later dismissed

2023-04-04 06:14 UTC, vikcool2pr requested changes

2023-04-04 07:23 UTC, arunmohanpk commented on web-components/src/components/button/Button.ts
> +    @property({ type: Boolean }) ariaHaspopup = undefined;
Done

2023-04-04 07:26 UTC, vikcool2pr approved these changes

2023-04-04 09:54 UTC, vinitkumargoel approved these changes

2023-04-04 10:07 UTC, merged