#CX-12023 : Troubleshooting and Fixing High Memory Issue in Accordion Web Component
momentum-design/momentum-ui pull request #1476
Opened 2023-09-05 08:38 UTC by prakhar-tiwari

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots:
**Before** (If applicable):

**After**:

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-09-05 11:03 UTC, parsoman approved these changes

2023-09-05 13:27 UTC, merajcal requested changes

2023-09-08 05:37 UTC, prakhar-tiwari commented on web-components/src/components/menu-overlay/MenuOverlay.ts
> +              document.dispatchEvent(new CustomEvent("on-widget-update"));
This is not documented event

2023-09-11 05:06 UTC, parsoman approved these changes

2023-09-11 06:46 UTC, merajcal approved these changes

2023-09-11 06:47 UTC, merged