fix(accessibility): implement dynamic label for 'Resize Modal'
momentum-design/momentum-ui pull request #1530
Opened 2024-02-12 08:46 UTC by iruchipriya

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots:
**Before** (If applicable):

**After**:

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-02-13 04:34 UTC, merajcal requested changes

2024-02-13 04:34 UTC, merajcal commented on web-components/src/components/floating-modal/FloatingModal.ts
> +                    aria-label="${this.full ? 'Fullscreen Resize Modal' : 'Halfscreen Resize Modal'}"
is this maximize and restore?
change the text

'Maximize the modal' : 'Restore the maximised modal', But this should not hard coded inside the component. the localized message should be passed by client code e.g. desktop

2024-02-13 04:44 UTC, vinitkumargoel commented
@iruchipriya  You need to update momentum version also

2024-02-15 04:25 UTC, merajcal requested changes

2024-02-15 04:25 UTC, merajcal commented on web-components/src/components/floating-modal/FloatingModal.ts
> +        new CustomEvent("floating-modal-fullscreen", {
rename event to maximize-restore-event

2024-02-15 05:27 UTC, iruchipriya commented on web-components/src/components/floating-modal/FloatingModal.ts
> +        new CustomEvent("floating-modal-fullscreen", {
updated

2024-02-15 11:33 UTC, merajcal approved these changes

2024-02-16 07:37 UTC, rathnavel commented on web-components/src/components/floating-modal/FloatingModal.ts
> +    @property({ type: String, attribute: "maximize-aria-label" }) maximizeScreenLabel  = "Maximize modal";
Change "modal" to "Modal"

2024-02-16 07:37 UTC, rathnavel approved these changes

2024-02-16 07:38 UTC, rathnavel approved these changes

2024-02-16 08:54 UTC, merajcal approved these changes

2024-02-16 08:55 UTC, merged