#CX-12968 : Handling second time sign in scenario for not showing emergency notification
momentum-design/momentum-ui pull request #1547
Opened 2024-02-20 19:14 UTC by rituparnadey1807

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots:
**Before** (If applicable):

**After**:

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-02-20 19:17 UTC, vinitkumargoel requested changes

2024-02-20 19:17 UTC, vinitkumargoel commented on web-components/package.json
> +  "version": "2.8.5",
increment only 1 not 5

2024-02-20 19:20 UTC, vinitkumargoel approved these changes

2024-02-21 05:48 UTC, merajcal approved these changes

2024-02-21 05:48 UTC, merged