Added Error message in aria label based on props
momentum-design/momentum-ui pull request #1548
Opened 2024-02-21 06:56 UTC by vinitkumargoel

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots:
**Before** (If applicable):

**After**:

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-02-21 07:05 UTC, akshatatray requested changes

2024-02-21 07:05 UTC, akshatatray commented on web-components/src/components/phone-input/PhoneInput.ts
> +      console.log("vinitkum, addDialNumberErrorInAriaLabel", this.addDialNumberErrorInAriaLabel)
@vinitkumargoel I guess this was pushed by mistake.

2024-02-21 07:22 UTC, akshatatray submitted a review, later dismissed

2024-02-23 05:10 UTC, adi2911 approved these changes

2024-02-23 06:32 UTC, merajcal requested changes

2024-02-23 06:32 UTC, merajcal commented on web-components/src/components/phone-input/PhoneInput.ts
> +    @property({ type: Boolean }) addDialNumberErrorInAriaLabel = false;
This flag seems unnecessary,

2024-02-26 06:23 UTC, merajcal approved these changes

2024-02-27 07:50 UTC, merged