#CX-10241 : Keyboard Shortcuts: Keyboard Navigation: Each row in table is tab focusable.
momentum-design/momentum-ui pull request #1608
Opened 2024-05-07 08:07 UTC by NamanGoel20

Added a property called "isRowFocusable" in the advanced table component, which when "true" will make the rows focusable via tab. If false, the rows will be skipped while tabbing.

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots:
**Before** (If applicable):

**After**:

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-05-07 10:26 UTC, neelabhnagaich submitted a review, later dismissed

2024-05-09 07:08 UTC, vinitkumargoel approved these changes

2024-05-09 07:08 UTC, vinitkumargoel requested changes
Please add sandbox and storybook example

2024-05-10 05:27 UTC, neelabhnagaich approved these changes

2024-05-10 05:28 UTC, vinitkumargoel approved these changes

2024-05-10 05:28 UTC, merged