New Component: DateTimePicker [CAX-774]
momentum-design/momentum-ui pull request #727
Opened 2020-12-10 03:57 UTC by elenagiere

DateTimePicker: combine datePicker and timePicker into one component.

Pending:
- Storybook
- more unit tests

## Description
The selection of a date and time is possible with this component.
There is a plethora of properties to customize this dateTimePicker.

## Related Issue

## Motivation and Context
New Component!
![Screen Shot 2020-12-09 at 7 54 39 PM](https://user-images.githubusercontent.com/15151981/101719548-6458b400-3a58-11eb-87fc-eb065649825a.png)

Figma Link: https://www.figma.com/file/wDbhcTS6fYP9wFyJ7VnE0r/Lumos-Components?node-id=11077%3A95346

## How Has This Been Tested?

## Screenshots:
**Before** (If applicable):

**After**:

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2020-12-10 17:58 UTC, futurethang requested changes

2020-12-10 17:58 UTC, futurethang commented on web-components/src/components/timepicker/TimePicker.ts
>          class="amPm-combo-box"
Nit: when typing in this box it uses lowercase, but options are uppercase. Maybe `text-transform:uppercase` will do the trick.

2020-12-10 19:50 UTC, yananym commented on web-components/src/components/combobox/ComboBox.ts
> +  @property({ type: Boolean }) selectWhenInFocus = false;
do we want this to be an attribute? with a lower case - dash naming?

2020-12-10 19:51 UTC, yananym commented on web-components/src/components/datepicker/DatePicker.ts
> +  @property({ type: Boolean }) shouldCloseOnSelect = false;
do we want this to be an attribute also?

2020-12-10 19:52 UTC, yananym commented on web-components/src/components/input/Input.ts
> +  @property({ type: Boolean }) selectWhenInFocus = false;
and here

2020-12-10 19:53 UTC, yananym commented on web-components/src/components/timepicker/TimePicker.ts
> +  @property({ type: Boolean }) twoDigitAutoTab = false;
all booleans basically need to also have an attribute friendly name (no camelCase)

2020-12-10 19:54 UTC, yananym commented on web-components/src/components/date-time-picker/DateTimePicker.ts
> +  @property({ type: Boolean }) twoDigitAutoTab = false;
attributes please?

2020-12-11 17:23 UTC, futurethang submitted a review, later dismissed

2020-12-12 02:46 UTC, yananym approved these changes

2020-12-12 02:47 UTC, merged