feat(core/list/space-list/popover): theming changes
momentum-design/momentum-ui pull request #882
Opened 2021-05-06 09:35 UTC by torgeadelin

## Description

The scope of the changes in this pull request are to add css theming variables to the input core component.
[SPARK-230827](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-230827)

## Motivation and Context

The changes in this PR are to meet presented requirements for the new theming.

## How Has This Been Tested?

## Screenshots:
Live user testing was done to confirm that the changes properly impacted the components without impacting existing use cases.

### Popover
Before:
![image](https://user-images.githubusercontent.com/14194394/117275957-7c413200-ae56-11eb-8dfa-6eee5530f596.png)

After:
![image](https://user-images.githubusercontent.com/14194394/117204255-f9818e00-ade7-11eb-89e7-a93540c2f403.png)

### Space List
Before:
![image](https://user-images.githubusercontent.com/14194394/117276297-a7c41c80-ae56-11eb-99ca-d0b9e58c8302.png)

After:
![image](https://user-images.githubusercontent.com/14194394/117204382-259d0f00-ade8-11eb-8b5a-d3f0661a1229.png)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [x] Other... Please describe:

- `mixin scrollbar()` has been changed slightly (in addition to the theming changes).
The first variable has been changed to just `border-color` instead of providing the whole border css value (eg 4px solid ...). All instances of `@include` were having the exact same value.
- for the `Popover` component, I replaced the border trick using `box-shadow` with proper `border`. The reason for this is because if you have a `List` inside the popover, the hover of the list-items would cover the border. Using `border` adds the border outside (outset instead of inset) of the container, fixing this issue.

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-05-18 10:02 UTC, torgeadelin commented
Thanks @futurethang, I'll ask somebody from my team to review it.

@InteractiveTimmy @robstax could you have a look at this when you get the chance?

2021-05-20 01:31 UTC, InteractiveTimmy requested changes
Small change request, If all tests pass within reason, I'll approve after changes are made.

2021-05-20 01:31 UTC, InteractiveTimmy commented on core/scss/tools/mixins/scrollbar.scss
> +  $border-color,
Good refactor with `$border` to `$border-color`

2021-05-20 01:31 UTC, InteractiveTimmy commented on core/scss/tools/mixins/scrollbar.scss
> +    background: var($foreground-css-var);
This needs a default, right?

```scss
background: var($foreground-css-var, $foreground);
```

2021-05-20 12:54 UTC, torgeadelin commented on core/scss/tools/mixins/scrollbar.scss
> +    background: var($foreground-css-var);
good catch!

2021-05-20 20:34 UTC, InteractiveTimmy submitted a review, later dismissed
LGTM

2021-05-21 16:40 UTC, yjlo approved these changes
LGTM

2021-05-21 16:41 UTC, merged